services:
  pipeline:
    image: wne3containers.azurecr.io/backend-pipeline:v0.1.1
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/app/ollama
    command: ["ollama", "pull", "artifish/llama3.2-uncensored:latest"]

volumes:
  ollama: